//! The options the compositor reads, with their types and defaults.
//!
//! Names are Hyprland's, written as `hyprctl getoption` writes them:
//! category, colon, name. The table holds *every* option Hyprland 0.56 has,
//! with its default, whether or not this compositor acts on it: the names
//! and the defaults are `ConfigValues.cpp`'s, in its order of types and
//! sorted by name here.
//!
//! Carrying them all is what lets a person's configuration be read rather
//! than argued with. Hyprland answers `config option does not exist` for a
//! name it has never heard of, and that is the right answer for a typo --
//! but it is the wrong answer for an option Hyprland has and this
//! compositor has not got round to, because then a working line becomes a
//! diagnostic and the person is told their file is wrong when it is not.
//! An option here that nothing reads still holds what was written, still
//! comes back from `hyprctl getoption`, and is still there for whatever
//! reads it later.
//!
//! The differential harness compares the defaults with `hyprctl getoption`
//! on a real Hyprland.

use core::fmt;

use crate::value::{self, Color, Gaps, Gradient};

/// An option's value.
#[derive(Debug, Clone, PartialEq)]
pub enum OptionValue {
    /// An integer, which is also how Hyprland stores booleans and colours.
    Int(i64),
    /// A float.
    Float(f64),
    /// A string, kept as written.
    Str(String),
    /// A border gradient.
    Gradient(Gradient),
    /// Gaps on four sides.
    Gaps(Gaps),
}

impl fmt::Display for OptionValue {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Int(value) => write!(f, "{value}"),
            Self::Float(value) => write!(f, "{value:.6}"),
            Self::Str(value) => f.write_str(value),
            Self::Gradient(value) => write!(f, "{value}"),
            Self::Gaps(value) => write!(f, "{value}"),
        }
    }
}

/// An option's default, in a form a `static` table can hold.
#[derive(Debug, Clone, Copy)]
pub(crate) enum Initial {
    Int(i64),
    Float(f64),
    Str(&'static str),
    Gradient(u32),
    Gaps(i64),
}

impl Initial {
    /// The value this default stands for.
    pub(crate) fn value(self) -> OptionValue {
        match self {
            Self::Int(value) => OptionValue::Int(value),
            Self::Float(value) => OptionValue::Float(value),
            Self::Str(value) => OptionValue::Str(value.to_owned()),
            Self::Gradient(color) => OptionValue::Gradient(Gradient::solid(Color(color))),
            Self::Gaps(gap) => OptionValue::Gaps(Gaps::all(gap)),
        }
    }

    /// Parse `text` as a value of this default's type.
    pub(crate) fn parse(self, text: &str) -> Result<OptionValue, String> {
        match self {
            Self::Int(_) => value::parse_int(text).map(OptionValue::Int),
            Self::Float(_) => value::parse_float(text).map(OptionValue::Float),
            Self::Str(_) => Ok(OptionValue::Str(text.trim().to_owned())),
            Self::Gradient(_) => value::parse_gradient(text).map(OptionValue::Gradient),
            Self::Gaps(_) => value::parse_gaps(text).map(OptionValue::Gaps),
        }
    }
}

use Initial::{Float, Gaps as GapsOf, Gradient as GradientOf, Int, Str};

/// Every option the compositor implements, sorted by name.
pub(crate) static OPTIONS: &[(&str, Initial)] = &[
    ("animations:enabled", Int(1)),
    ("animations:workspace_wraparound", Int(0)),
    ("binds:allow_pin_fullscreen", Int(0)),
    ("binds:allow_workspace_cycles", Int(0)),
    ("binds:disable_keybind_grabbing", Int(0)),
    ("binds:drag_threshold", Int(0)),
    ("binds:focus_preferred_method", Int(0)),
    ("binds:hide_special_on_workspace_change", Int(0)),
    ("binds:ignore_group_lock", Int(0)),
    ("binds:movefocus_cycles_fullscreen", Int(0)),
    ("binds:movefocus_cycles_groupfirst", Int(0)),
    ("binds:pass_mouse_when_bound", Int(0)),
    ("binds:scroll_event_delay", Int(300)),
    ("binds:window_direction_monitor_fallback", Int(1)),
    ("binds:workspace_back_and_forth", Int(0)),
    ("binds:workspace_center_on", Int(1)),
    ("cursor:default_monitor", Str("")),
    ("cursor:enable_hyprcursor", Int(1)),
    ("cursor:hide_on_key_press", Int(0)),
    ("cursor:hide_on_tablet", Int(0)),
    ("cursor:hide_on_touch", Int(1)),
    ("cursor:hotspot_padding", Int(0)),
    ("cursor:inactive_timeout", Float(0.0)),
    ("cursor:invisible", Int(0)),
    ("cursor:min_refresh_rate", Int(24)),
    ("cursor:no_break_fs_vrr", Int(2)),
    ("cursor:no_hardware_cursors", Int(2)),
    ("cursor:no_warps", Int(0)),
    ("cursor:persistent_warps", Int(0)),
    ("cursor:sync_gsettings_theme", Int(1)),
    ("cursor:use_cpu_buffer", Int(2)),
    ("cursor:warp_back_after_non_mouse_input", Int(0)),
    ("cursor:warp_on_change_workspace", Int(0)),
    ("cursor:warp_on_toggle_special", Int(0)),
    ("cursor:zoom_detached_camera", Int(1)),
    ("cursor:zoom_disable_aa", Int(0)),
    ("cursor:zoom_factor", Float(1.0)),
    ("cursor:zoom_rigid", Int(0)),
    ("debug:colored_stdout_logs", Int(1)),
    ("debug:damage_blink", Int(0)),
    ("debug:damage_tracking", Int(2)),
    ("debug:disable_logs", Int(1)),
    ("debug:disable_scale_checks", Int(0)),
    ("debug:disable_time", Int(1)),
    ("debug:ds_handle_same_buffer", Int(1)),
    ("debug:ds_handle_same_buffer_fifo", Int(1)),
    ("debug:enable_stdout_logs", Int(0)),
    ("debug:error_limit", Int(5)),
    ("debug:error_position", Int(0)),
    ("debug:fifo_pending_workaround", Int(0)),
    ("debug:full_cm_proto", Int(0)),
    ("debug:gl_debugging", Int(0)),
    ("debug:invalidate_fp16", Int(1)),
    ("debug:log_damage", Int(0)),
    ("debug:manual_crash", Int(0)),
    ("debug:overlay", Int(0)),
    ("debug:pass", Int(0)),
    ("debug:render_solitary_wo_damage", Int(0)),
    ("debug:suppress_errors", Int(0)),
    ("debug:vfr", Int(1)),
    ("decoration:active_opacity", Float(1.0)),
    ("decoration:blur:brightness", Float(1.0)),
    ("decoration:blur:contrast", Float(0.8916)),
    ("decoration:blur:enabled", Int(1)),
    ("decoration:blur:ignore_opacity", Int(1)),
    ("decoration:blur:input_methods", Int(0)),
    ("decoration:blur:input_methods_ignorealpha", Float(0.2)),
    ("decoration:blur:new_optimizations", Int(1)),
    ("decoration:blur:noise", Float(0.0117)),
    ("decoration:blur:passes", Int(1)),
    ("decoration:blur:popups", Int(0)),
    ("decoration:blur:popups_ignorealpha", Float(0.2)),
    ("decoration:blur:size", Int(8)),
    ("decoration:blur:special", Int(0)),
    ("decoration:blur:vibrancy", Float(0.1696)),
    ("decoration:blur:vibrancy_darkness", Float(0.0)),
    ("decoration:blur:xray", Int(0)),
    ("decoration:border_part_of_window", Int(1)),
    ("decoration:dim_around", Float(0.4)),
    ("decoration:dim_inactive", Int(0)),
    ("decoration:dim_modal", Int(1)),
    ("decoration:dim_special", Float(0.2)),
    ("decoration:dim_strength", Float(0.5)),
    ("decoration:fullscreen_opacity", Float(1.0)),
    ("decoration:glow:color", GradientOf(0xee33_ccff)),
    ("decoration:glow:color_inactive", Int(-1)),
    ("decoration:glow:enabled", Int(0)),
    ("decoration:glow:range", Int(10)),
    ("decoration:glow:render_power", Int(3)),
    ("decoration:inactive_opacity", Float(1.0)),
    ("decoration:motion_blur:enabled", Int(0)),
    ("decoration:motion_blur:samples", Int(7)),
    ("decoration:rounding", Int(0)),
    ("decoration:rounding_power", Float(2.0)),
    ("decoration:screen_shader", Str("")),
    ("decoration:shadow:color", GradientOf(0xee1a_1a1a)),
    ("decoration:shadow:color_inactive", Int(-1)),
    ("decoration:shadow:enabled", Int(1)),
    ("decoration:shadow:offset", Str("0 0")),
    ("decoration:shadow:range", Int(4)),
    ("decoration:shadow:render_power", Int(3)),
    ("decoration:shadow:scale", Float(1.0)),
    ("decoration:shadow:sharp", Int(0)),
    ("dwindle:default_split_ratio", Float(1.0)),
    ("dwindle:force_split", Int(0)),
    ("dwindle:permanent_direction_override", Int(0)),
    ("dwindle:precise_mouse_move", Int(0)),
    ("dwindle:preserve_split", Int(0)),
    ("dwindle:pseudotile", Int(0)),
    ("dwindle:smart_resizing", Int(1)),
    ("dwindle:smart_split", Int(0)),
    ("dwindle:special_scale_factor", Float(1.0)),
    ("dwindle:split_bias", Int(0)),
    ("dwindle:split_width_multiplier", Float(1.0)),
    ("dwindle:use_active_for_splits", Int(1)),
    ("ecosystem:enforce_permissions", Int(0)),
    ("ecosystem:no_donation_nag", Int(0)),
    ("ecosystem:no_update_news", Int(0)),
    ("experimental:wp_cm_1_2", Int(1)),
    ("general:allow_tearing", Int(0)),
    ("general:border_size", Int(1)),
    ("general:col.active_border", GradientOf(0xffff_ffff)),
    ("general:col.inactive_border", GradientOf(0xff44_4444)),
    ("general:col.nogroup_border", GradientOf(0xffff_aaff)),
    ("general:col.nogroup_border_active", GradientOf(0xffff_00ff)),
    ("general:extend_border_grab_area", Int(15)),
    ("general:float_gaps", GapsOf(0)),
    ("general:gaps_in", GapsOf(5)),
    ("general:gaps_out", GapsOf(20)),
    ("general:gaps_workspaces", Int(0)),
    ("general:hover_icon_on_border", Int(1)),
    ("general:layout", Str("dwindle")),
    ("general:locale", Str("")),
    ("general:modal_parent_blocking", Int(1)),
    ("general:no_focus_fallback", Int(0)),
    ("general:resize_corner", Int(0)),
    ("general:resize_on_border", Int(0)),
    ("general:snap:border_overlap", Int(0)),
    ("general:snap:enabled", Int(0)),
    ("general:snap:monitor_gap", Int(10)),
    ("general:snap:respect_gaps", Int(0)),
    ("general:snap:window_gap", Int(10)),
    ("gestures:close_max_timeout", Int(1000)),
    ("gestures:scrolling:move_snap_cursor", Int(1)),
    ("gestures:scrolling:move_snap_to_grid", Int(1)),
    ("gestures:workspace_swipe_cancel_ratio", Float(0.5)),
    ("gestures:workspace_swipe_create_new", Int(1)),
    ("gestures:workspace_swipe_direction_lock", Int(1)),
    ("gestures:workspace_swipe_direction_lock_threshold", Int(10)),
    ("gestures:workspace_swipe_distance", Int(300)),
    ("gestures:workspace_swipe_forever", Int(0)),
    ("gestures:workspace_swipe_invert", Int(1)),
    ("gestures:workspace_swipe_min_speed_to_force", Int(30)),
    ("gestures:workspace_swipe_touch", Int(0)),
    ("gestures:workspace_swipe_touch_invert", Int(0)),
    ("gestures:workspace_swipe_use_r", Int(0)),
    ("group:auto_group", Int(1)),
    ("group:col.border_active", GradientOf(0x66ff_ff00)),
    ("group:col.border_inactive", GradientOf(0x6677_7700)),
    ("group:col.border_locked_active", GradientOf(0x6677_5500)),
    ("group:col.border_locked_inactive", GradientOf(0x66ff_5500)),
    ("group:drag_into_group", Int(1)),
    ("group:focus_removed_window", Int(1)),
    ("group:group_on_movetoworkspace", Int(0)),
    ("group:groupbar:blur", Int(0)),
    ("group:groupbar:col.active", GradientOf(0x66ff_ff00)),
    ("group:groupbar:col.inactive", GradientOf(0x6677_7700)),
    ("group:groupbar:col.locked_active", GradientOf(0x66ff_5500)),
    (
        "group:groupbar:col.locked_inactive",
        GradientOf(0x6677_5500),
    ),
    ("group:groupbar:disable_when_only", Int(0)),
    ("group:groupbar:enabled", Int(1)),
    ("group:groupbar:font_family", Str("[[EMPTY]]")),
    ("group:groupbar:font_size", Int(8)),
    ("group:groupbar:gaps_in", Int(2)),
    ("group:groupbar:gaps_out", Int(2)),
    ("group:groupbar:gradient_round_only_edges", Int(1)),
    ("group:groupbar:gradient_rounding", Int(2)),
    ("group:groupbar:gradient_rounding_power", Float(2.0)),
    ("group:groupbar:gradients", Int(0)),
    ("group:groupbar:height", Int(14)),
    ("group:groupbar:indicator_gap", Int(0)),
    ("group:groupbar:indicator_height", Int(3)),
    ("group:groupbar:keep_upper_gap", Int(1)),
    ("group:groupbar:middle_click_close", Int(1)),
    ("group:groupbar:priority", Int(3)),
    ("group:groupbar:render_titles", Int(1)),
    ("group:groupbar:round_only_edges", Int(1)),
    ("group:groupbar:rounding", Int(1)),
    ("group:groupbar:rounding_power", Float(2.0)),
    ("group:groupbar:scrolling", Int(1)),
    ("group:groupbar:stacked", Int(0)),
    ("group:groupbar:text_color", GradientOf(0xffff_ffff)),
    ("group:groupbar:text_color_inactive", Int(-1)),
    ("group:groupbar:text_color_locked_active", Int(-1)),
    ("group:groupbar:text_color_locked_inactive", Int(-1)),
    ("group:groupbar:text_offset", Int(0)),
    ("group:groupbar:text_padding", Int(0)),
    ("group:insert_after_current", Int(1)),
    ("group:merge_floated_into_tiled_on_groupbar", Int(0)),
    ("group:merge_groups_on_drag", Int(1)),
    ("group:merge_groups_on_groupbar", Int(1)),
    ("input-capture:capture_modifiers", Int(0)),
    ("input-capture:enforce_barriers", Int(1)),
    ("input:accel_profile", Str("")),
    ("input:emulate_discrete_scroll", Int(1)),
    ("input:focus_on_close", Int(0)),
    ("input:follow_mouse", Int(1)),
    ("input:follow_mouse_threshold", Float(0.0)),
    ("input:force_no_accel", Int(0)),
    ("input:kb_file", Str("")),
    ("input:kb_layout", Str("us")),
    ("input:kb_model", Str("")),
    ("input:kb_options", Str("")),
    ("input:kb_rules", Str("")),
    ("input:kb_variant", Str("")),
    ("input:left_handed", Int(0)),
    ("input:mouse_refocus", Int(1)),
    ("input:natural_scroll", Int(0)),
    ("input:numlock_by_default", Int(0)),
    ("input:off_window_axis_events", Int(1)),
    ("input:repeat_delay", Int(600)),
    ("input:repeat_rate", Int(25)),
    ("input:resolve_binds_by_sym", Int(0)),
    ("input:rotation", Int(0)),
    ("input:scroll_button", Int(0)),
    ("input:scroll_button_lock", Int(0)),
    ("input:scroll_factor", Float(1.0)),
    ("input:scroll_method", Str("")),
    ("input:scroll_points", Str("")),
    ("input:sensitivity", Float(0.0)),
    ("input:special_fallthrough", Int(0)),
    ("input:tablet:absolute_region_position", Int(0)),
    ("input:tablet:active_area_position", Str("0 0")),
    ("input:tablet:active_area_size", Str("0 0")),
    ("input:tablet:left_handed", Int(0)),
    ("input:tablet:output", Str("")),
    ("input:tablet:region_position", Str("0 0")),
    ("input:tablet:region_size", Str("0 0")),
    ("input:tablet:relative_input", Int(0)),
    ("input:tablet:transform", Int(0)),
    ("input:tablettool:pressure_range_max", Float(-1.0)),
    ("input:tablettool:pressure_range_min", Float(-1.0)),
    ("input:touchdevice:enabled", Int(1)),
    ("input:touchdevice:output", Str("[[Auto]]")),
    ("input:touchdevice:transform", Int(0)),
    ("input:touchpad:clickfinger_behavior", Int(0)),
    ("input:touchpad:disable_while_typing", Int(1)),
    ("input:touchpad:drag_3fg", Int(0)),
    ("input:touchpad:drag_lock", Int(0)),
    ("input:touchpad:flip_x", Int(0)),
    ("input:touchpad:flip_y", Int(0)),
    ("input:touchpad:middle_button_emulation", Int(0)),
    ("input:touchpad:natural_scroll", Int(0)),
    ("input:touchpad:scroll_factor", Float(1.0)),
    ("input:touchpad:tap-and-drag", Int(1)),
    ("input:touchpad:tap-to-click", Int(1)),
    ("input:touchpad:tap_button_map", Str("")),
    ("input:virtualkeyboard:release_pressed_on_close", Int(0)),
    ("input:virtualkeyboard:share_states", Int(2)),
    ("layout:single_window_aspect_ratio", Str("0 0")),
    ("layout:single_window_aspect_ratio_tolerance", Float(0.1)),
    ("master:allow_small_split", Int(0)),
    ("master:always_keep_position", Int(0)),
    ("master:center_ignores_reserved", Int(0)),
    ("master:center_master_fallback", Str("left")),
    ("master:drop_at_cursor", Int(1)),
    ("master:focus_master_on_close", Int(0)),
    ("master:inherit_fullscreen", Int(1)),
    ("master:mfact", Float(0.55)),
    ("master:new_on_active", Str("none")),
    ("master:new_on_top", Int(0)),
    ("master:new_status", Str("slave")),
    ("master:orientation", Str("left")),
    ("master:slave_count_for_center_master", Int(2)),
    ("master:smart_resizing", Int(1)),
    ("master:special_scale_factor", Float(1.0)),
    ("misc:allow_session_lock_restore", Int(0)),
    ("misc:always_follow_on_dnd", Int(1)),
    ("misc:animate_manual_resizes", Int(0)),
    ("misc:animate_mouse_windowdragging", Int(0)),
    ("misc:anr_missed_pings", Int(5)),
    ("misc:background_color", GradientOf(0xff11_1111)),
    ("misc:close_special_on_empty", Int(1)),
    ("misc:col.splash", GradientOf(0x55ff_ffff)),
    ("misc:disable_autoreload", Int(0)),
    ("misc:disable_hyprland_guiutils_check", Int(0)),
    ("misc:disable_hyprland_logo", Int(0)),
    ("misc:disable_scale_notification", Int(0)),
    ("misc:disable_splash_rendering", Int(0)),
    ("misc:disable_watchdog_warning", Int(0)),
    ("misc:disable_xdg_env_checks", Int(0)),
    ("misc:enable_anr_dialog", Int(1)),
    ("misc:enable_swallow", Int(0)),
    ("misc:exit_window_retains_fullscreen", Int(0)),
    ("misc:focus_on_activate", Int(0)),
    ("misc:font_family", Str("Sans")),
    ("misc:force_default_wallpaper", Int(-1)),
    ("misc:initial_workspace_token_timeout", Int(10)),
    ("misc:initial_workspace_tracking", Int(1)),
    ("misc:key_press_enables_dpms", Int(0)),
    ("misc:layers_hog_keyboard_focus", Int(1)),
    ("misc:lockdead_screen_delay", Int(1000)),
    ("misc:middle_click_paste", Int(1)),
    ("misc:mouse_move_enables_dpms", Int(0)),
    ("misc:mouse_move_focuses_monitor", Int(1)),
    ("misc:name_vk_after_proc", Int(1)),
    ("misc:on_focus_under_fullscreen", Int(2)),
    ("misc:render_unfocused_fps", Int(15)),
    ("misc:screencopy_force_8b", Int(1)),
    ("misc:session_lock_blur", Int(0)),
    ("misc:session_lock_xray", Int(0)),
    ("misc:size_limits_tiled", Int(0)),
    ("misc:splash_font_family", Str("[[EMPTY]]")),
    ("misc:swallow_exception_regex", Str("")),
    ("misc:swallow_regex", Str("")),
    ("misc:vrr", Int(0)),
    ("opengl:nvidia_anti_flicker", Int(1)),
    ("quirks:prefer_hdr", Int(0)),
    ("quirks:skip_non_kms_dmabuf_formats", Int(0)),
    ("render:cm_auto_hdr", Int(1)),
    ("render:cm_enabled", Int(1)),
    ("render:cm_sdr_eotf", Str("default")),
    ("render:commit_timing_enabled", Int(1)),
    ("render:ctm_animation", Int(2)),
    ("render:direct_scanout", Int(0)),
    ("render:expand_undersized_textures", Int(1)),
    ("render:fp16_sdr_tf", Int(0)),
    ("render:icc_vcgt_enabled", Int(1)),
    ("render:keep_unmodified_copy", Int(2)),
    ("render:new_render_scheduling", Int(0)),
    ("render:non_shader_cm", Int(3)),
    ("render:non_shader_cm_interop", Int(2)),
    ("render:send_content_type", Int(1)),
    ("render:use_fp16", Int(2)),
    ("render:use_shader_blur_blend", Int(0)),
    ("render:xp_mode", Int(0)),
    ("scrolling:column_width", Float(0.5)),
    ("scrolling:direction", Str("right")),
    (
        "scrolling:explicit_column_widths",
        Str("0.333, 0.5, 0.667, 1.0"),
    ),
    ("scrolling:focus_fit_method", Int(1)),
    ("scrolling:follow_focus", Int(1)),
    ("scrolling:follow_min_visible", Float(0.4)),
    ("scrolling:fullscreen_on_one_column", Int(1)),
    ("scrolling:wrap_focus", Int(1)),
    ("scrolling:wrap_swapcol", Int(1)),
    ("xwayland:create_abstract_socket", Int(0)),
    ("xwayland:enabled", Int(1)),
    ("xwayland:force_zero_scaling", Int(0)),
    ("xwayland:use_nearest_neighbor", Int(1)),
];

/// What the table says an option starts as, if the compositor has it.
///
/// `hyprctl getoption` prints a `set` flag, which is whether the
/// configuration said anything about the option rather than leaving it at
/// this.
#[must_use]
pub fn default_of(name: &str) -> Option<OptionValue> {
    find(name).map(Initial::value)
}

/// The table entry for `name`, if the compositor has that option.
pub(crate) fn find(name: &str) -> Option<Initial> {
    OPTIONS
        .binary_search_by(|(entry, _)| (*entry).cmp(name))
        .ok()
        .and_then(|index| OPTIONS.get(index))
        .map(|&(_, default)| default)
}
