//! The Vivante GC400T in an STM32MP157 as logic over registers and command
//! memory: who the core says it is, how it is brought out of reset, and the
//! command stream its front end fetches.
//!
//! `user/gc400` runs this in a ring-3 process under devmgr (`docs/GPU.md`
//! §6.3). The process holds an `IoMapping` of the core's registers, its
//! interrupt, and a page pinned with `PIN_COHERENT` for the command buffer.
//! None of those exist in a unit test, so everything that decides a register
//! value or a command word is here, written against [`Registers`],
//! [`Clock`] and [`ring::CommandMemory`], and tested against a model of the
//! core's host interface and of its front end:
//!
//! * [`regs`]: the register offsets and bitfields used;
//! * [`stream`]: the front end's commands, one 64-bit slot each;
//! * [`identity`]: the chip's identification registers, read as etnaviv
//!   reads them, and what they mean for how the core is addressed;
//! * [`bringup`]: the soft reset and the initialisation a core needs before
//!   its front end is started;
//! * [`ring`]: a `WAIT`/`LINK` loop the front end idles in, and blocks of
//!   commands spliced into it, each ending in an event.
//!
//! # Where the numbers come from
//!
//! Every register offset, bitfield and command encoding is from the etnaviv
//! project's register database, generated by rules-ng-ng from its XML and
//! published under the MIT licence:
//!
//! * `cmdstream.xml.h`, `common.xml.h` and `state.xml.h`, as Mesa 26.2.3
//!   carries them in `src/etnaviv/hw/`: the command stream, the feature bits,
//!   and the front end's and the `GL` block's states;
//! * `state_hi.xml.h`, the host interface, the power management block and
//!   the memory controller, generated from the same database by the same
//!   authors but carried by Linux's `drivers/gpu/drm/etnaviv/` rather than by
//!   Mesa.
//!
//! The *sequence* -- what is written in which order, and which checks a
//! reset has to pass -- was learned by reading Linux's etnaviv driver
//! (`etnaviv_gpu.c`, `etnaviv_buffer.c`, `etnaviv_iommu*.c`,
//! `etnaviv_hwdb.c`). That driver is GPL-2.0 and none of its code is here:
//! each step below names the function it follows and says why the step is
//! needed, in words of this crate's own.
//!
//! # What the kernel has already done
//!
//! The RCC is not a driver's: it clocks every peripheral on the chip. The
//! kernel turns on the GPU's bus and core clocks, pulses its reset line,
//! and checks that PLL2's Q output, the core clock, runs, before it
//! publishes the device (`kernel/src/stm32mp1_gpu.rs`). What reaches this
//! crate is a register window of a core fresh out of reset.

#![no_std]
#![forbid(unsafe_code)]

pub mod bringup;
pub mod identity;
pub mod regs;
pub mod ring;
pub mod stream;

#[cfg(test)]
extern crate std;

#[cfg(test)]
mod tests;

/// A window of 32-bit device registers, by byte offset.
pub trait Registers {
    /// Read the register at `offset`.
    fn read32(&self, offset: u32) -> u32;
    /// Write the register at `offset`.
    fn write32(&mut self, offset: u32, value: u32);
}

/// Time, for the waits a reset needs.
pub trait Clock {
    /// Monotonic nanoseconds.
    fn now_nanos(&self) -> u64;
    /// Wait at least `nanos`.
    fn sleep_nanos(&mut self, nanos: u64);
}

/// A microsecond, in [`Clock`]'s units.
pub const MICROSECOND: u64 = 1_000;
/// A millisecond, in [`Clock`]'s units.
pub const MILLISECOND: u64 = 1_000_000;
