//! Exception and interrupt entry on x86-64.
//!
//! # Why there is assembly here
//!
//! The CPU enters a handler with the interrupted program's registers still
//! live, having pushed a frame the shape of which *depends on the vector*: ten
//! of the 256 vectors push an error code and the rest do not. No Rust function
//! can be entered without a prologue that would destroy those registers, and no
//! Rust signature can describe a frame whose size varies.
//!
//! So the stubs below do three things and hand over: push a zero where the CPU
//! did not push an error code, so every frame has one shape; push the vector
//! number, so the handler knows why it was called; and save the general
//! registers in the order [`TrapFrame`] declares.
//!
//! The 256 stubs are generated by an assembler `.rept` rather than by a Rust
//! macro emitting 256 blocks. Both produce the same machine code; one is
//! fifteen lines on the assembly allow-list and the other is closer to eight
//! hundred.

use core::cell::UnsafeCell;

use super::cpu;
use super::gdt;

/// Vectors in an interrupt descriptor table. Fixed by the architecture.
const VECTORS: usize = 256;

/// Bytes each entry stub occupies. The stubs are `.align 16`, so stub `n` lives
/// at `ferrix_trap_stubs + n * STUB_SIZE` and the table can be built by
/// arithmetic rather than by 256 symbols.
const STUB_SIZE: usize = 16;

/// The register state at the point a trap was taken.
///
/// Field order is the order the entry stub pushes them, which is the reverse of
/// the order they appear in memory — the stack grows down, so the last register
/// pushed has the lowest address and is the first field.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub(crate) struct TrapFrame {
    pub(crate) r15: u64,
    pub(crate) r14: u64,
    pub(crate) r13: u64,
    pub(crate) r12: u64,
    pub(crate) r11: u64,
    pub(crate) r10: u64,
    pub(crate) r9: u64,
    pub(crate) r8: u64,
    pub(crate) rbp: u64,
    pub(crate) rdi: u64,
    pub(crate) rsi: u64,
    pub(crate) rdx: u64,
    pub(crate) rcx: u64,
    pub(crate) rbx: u64,
    pub(crate) rax: u64,

    /// Which vector was taken. Pushed by the stub.
    pub(crate) vector: u64,
    /// The CPU's error code, or zero where the CPU pushes none.
    pub(crate) error_code: u64,

    // Pushed by the CPU itself. `rsp` and `ss` are pushed unconditionally in
    // long mode, even for a trap that did not change privilege level — unlike
    // 32-bit x86, where they appear only on a ring change.
    pub(crate) rip: u64,
    pub(crate) cs: u64,
    pub(crate) rflags: u64,
    pub(crate) rsp: u64,
    pub(crate) ss: u64,
}

impl TrapFrame {
    /// True if the trap came from user mode, judged by the saved code segment's
    /// requested privilege level.
    pub(crate) const fn came_from_user(&self) -> bool {
        self.cs & 3 != 0
    }
}

core::arch::global_asm!(
    r#"
.section .text
.globl ferrix_trap_stubs
.align 16
ferrix_trap_stubs:
    .set vector, 0
    .rept 256
    .align 16
    .if (vector != 8) && (vector < 10 || vector > 14) && (vector != 17) && (vector != 21) && (vector != 29) && (vector != 30)
    pushq $0
    .endif
    pushq $vector
    jmp ferrix_trap_common
    .set vector, vector + 1
    .endr

ferrix_trap_common:
    pushq %rax
    pushq %rbx
    pushq %rcx
    pushq %rdx
    pushq %rsi
    pushq %rdi
    pushq %rbp
    pushq %r8
    pushq %r9
    pushq %r10
    pushq %r11
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    cld

    // If this trap came from ring 3, GS is the program's and every per-CPU
    // read in the handler would go through a pointer it chose. `swapgs` is
    // not idempotent and the processor will not say which way round GS is, so
    // the decision is made from the one thing that does say: the CS the
    // processor pushed. Offset 144 is `TrapFrame::cs`, which is asserted
    // against the struct in Rust rather than counted by hand here.
    testb $3, 144(%rsp)
    jz 1f
    swapgs
1:
    movq %rsp, %rdi
    callq ferrix_trap_entry

    // And back, on exactly the paths that swapped. The same test, because the
    // handler cannot have changed where the frame says it came from.
.globl ferrix_trap_return
ferrix_trap_return:
    testb $3, 144(%rsp)
    jz 2f
    swapgs
2:
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %r11
    popq %r10
    popq %r9
    popq %r8
    popq %rbp
    popq %rdi
    popq %rsi
    popq %rdx
    popq %rcx
    popq %rbx
    popq %rax
    addq $16, %rsp
    iretq

// Resume ring 3 from a whole frame, as `rt_sigreturn` must: every register,
// through the restore half above.
//   rdi = a `TrapFrame` from ring 3, on the running task's kernel stack
.globl ferrix_resume_trap_frame
ferrix_resume_trap_frame:
    cli
    movq %rdi, %rsp
    jmp ferrix_trap_return
"#,
    options(att_syntax)
);

/// The offset the trap stub uses to reach the saved `CS`.
///
/// The stub decides whether to `swapgs` by testing the privilege bits of the
/// `CS` the processor pushed, and it has to name that by a number. Asserting
/// it here means a field added to [`TrapFrame`] fails the build instead of
/// turning the test into a read of some other register -- which would swap
/// `GS` on the wrong paths and leave the kernel reading its per-CPU record
/// through whatever a program put there.
const _: () = assert!(
    core::mem::offset_of!(TrapFrame, cs) == 144,
    "the trap stub tests CS at 144(%rsp)"
);

unsafe extern "C" {
    /// The first of 256 entry stubs, each [`STUB_SIZE`] bytes apart.
    static ferrix_trap_stubs: [u8; VECTORS * STUB_SIZE];
}

/// One interrupt descriptor table entry.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
struct Gate {
    offset_low: u16,
    selector: u16,
    /// Bits 0..3 select an interrupt stack table slot; zero means do not switch.
    ist: u8,
    /// Present, privilege level, and gate type.
    flags: u8,
    offset_middle: u16,
    offset_high: u32,
    reserved: u32,
}

/// A 64-bit interrupt gate, present, callable only from ring 0.
///
/// An *interrupt* gate rather than a trap gate: it clears the interrupt flag on
/// entry, so a handler starts with interrupts masked and cannot be re-entered
/// by the same source before it has saved anything.
const INTERRUPT_GATE: u8 = 0x8E;

impl Gate {
    fn new(handler: u64, ist: u16) -> Gate {
        Gate {
            offset_low: handler as u16,
            selector: gdt::KERNEL_CODE,
            ist: (ist & 0b111) as u8,
            flags: INTERRUPT_GATE,
            offset_middle: (handler >> 16) as u16,
            offset_high: (handler >> 32) as u32,
            reserved: 0,
        }
    }
}

/// The table.
struct Idt(UnsafeCell<[Gate; VECTORS]>);

// SAFETY: written once by `init` on the boot CPU before interrupts are enabled,
// and read-only thereafter. Unlike the GDT this one genuinely can be shared by
// every CPU, because it holds no per-CPU state.
unsafe impl Sync for Idt {}

static IDT: Idt = Idt(UnsafeCell::new(
    [const {
        Gate {
            offset_low: 0,
            selector: 0,
            ist: 0,
            flags: 0,
            offset_middle: 0,
            offset_high: 0,
            reserved: 0,
        }
    }; VECTORS],
));

/// The operand `lidt` takes.
#[repr(C, packed)]
struct DescriptorTablePointer {
    limit: u16,
    base: u64,
}

/// Fill the interrupt descriptor table and load it.
///
/// # Safety
///
/// Must be called after [`gdt::init`], because every gate names the kernel code
/// selector that call installs.
pub(crate) unsafe fn init() {
    // SAFETY: single-threaded early boot, and this is the only writer.
    let table = unsafe { &mut *IDT.0.get() };
    let stubs = (&raw const ferrix_trap_stubs) as u64;

    for (vector, gate) in table.iter_mut().enumerate() {
        // The double fault is the one vector that cannot share the kernel
        // stack: it usually means that stack is unusable, and faulting again
        // inside the handler is a triple fault, which the CPU answers with a
        // silent reset and no diagnostic at all.
        let ist = if vector == 8 {
            gdt::DOUBLE_FAULT_IST
        } else {
            0
        };
        *gate = Gate::new(stubs + (vector * STUB_SIZE) as u64, ist);
    }

    // SAFETY: the table was filled just above, and the GDT is loaded.
    unsafe { load_on_this_cpu() };
}

/// Point this processor at the interrupt descriptor table.
///
/// One table serves every processor: it holds entry points and nothing that
/// belongs to any one of them.
///
/// # Safety
///
/// [`init`] must have filled the table, and this processor's GDT must hold a
/// 64-bit kernel code segment at the selector every gate names.
pub(crate) unsafe fn load_on_this_cpu() {
    let pointer = DescriptorTablePointer {
        limit: (size_of::<[Gate; VECTORS]>() - 1) as u16,
        base: IDT.0.get() as u64,
    };
    // SAFETY: `pointer` describes the one table, every gate of which points at
    // a stub in this image once `init` has run.
    unsafe { cpu::load_idt(&raw const pointer as u64) };
}

/// Where the entry stub hands over.
///
/// Not called from Rust — the `callq` in the assembly above is its only caller.
#[unsafe(no_mangle)]
extern "C" fn ferrix_trap_entry(frame: &mut TrapFrame) {
    crate::trap::dispatch(frame);
}

/// The address a page fault was taken on.
pub(crate) fn fault_address() -> u64 {
    cpu::read_cr2()
}

/// The architecture's name for a vector, for reporting.
pub(crate) const fn vector_name(vector: u64) -> &'static str {
    match vector {
        0 => "divide error",
        1 => "debug",
        2 => "non-maskable interrupt",
        3 => "breakpoint",
        4 => "overflow",
        5 => "bound range exceeded",
        6 => "invalid opcode",
        7 => "device not available",
        8 => "double fault",
        10 => "invalid TSS",
        11 => "segment not present",
        12 => "stack-segment fault",
        13 => "general protection fault",
        14 => "page fault",
        16 => "x87 floating-point exception",
        17 => "alignment check",
        18 => "machine check",
        19 => "SIMD floating-point exception",
        20 => "virtualisation exception",
        21 => "control protection exception",
        _ => "interrupt",
    }
}

/// The vector `int $0x80` raises: Linux's original 32-bit syscall entry.
const LEGACY_SYSCALL_VECTOR: u64 = 0x80;

/// The first vector the interrupt controller is allowed to use.
///
/// Vectors 0..31 are the CPU's own exceptions and are reserved by the
/// architecture, whatever the controller would prefer.
pub(crate) const IRQ_BASE: u64 = 32;

/// Page fault error code bit: a mapping existed and denied the access, rather
/// than there being no mapping at all.
const FAULT_PRESENT: u64 = 1 << 0;
/// Page fault error code bit: the access was a write.
const FAULT_WRITE: u64 = 1 << 1;
/// Page fault error code bit: the access came from user mode.
const FAULT_USER: u64 = 1 << 2;
/// Page fault error code bit: the access was an instruction fetch.
const FAULT_FETCH: u64 = 1 << 4;

/// Turn an x86-64 trap frame into the architecture-neutral description the
/// generic dispatcher works with.
pub(crate) fn classify(frame: &TrapFrame) -> crate::trap::Trap {
    use crate::trap::{PageFault, Trap};

    match frame.vector {
        3 => Trap::Breakpoint,
        6 => Trap::IllegalInstruction,
        // The legacy `int $0x80` entry. A 64-bit musl uses the `syscall`
        // instruction instead, which does not come through here at all, but a
        // 32-bit binary or an old static one still uses this and classifying it
        // correctly is free.
        LEGACY_SYSCALL_VECTOR => Trap::SystemCall,
        14 => Trap::PageFault(PageFault {
            address: fault_address(),
            write: frame.error_code & FAULT_WRITE != 0,
            execute: frame.error_code & FAULT_FETCH != 0,
            user: frame.error_code & FAULT_USER != 0,
            present: frame.error_code & FAULT_PRESENT != 0,
        }),
        vector if vector >= IRQ_BASE => Trap::Interrupt((vector - IRQ_BASE) as u32),
        vector => Trap::Fault {
            name: vector_name(vector),
            code: frame.error_code,
        },
    }
}

/// The signal Linux raises for a trap a program's own instruction took and
/// nothing resolved, as `(signal, si_code, si_addr)`: a page fault `SIGSEGV`
/// at the address, `#UD` `SIGILL` and `#DE` `SIGFPE` at the instruction,
/// `#MF` and `#XM` `SIGFPE`, `#AC` `SIGBUS`, a breakpoint `SIGTRAP`, and
/// everything else -- `#GP` from a privileged instruction, `#SS`, `#NP` --
/// `SIGSEGV` from the kernel with no address.
pub(crate) fn fault_signal(frame: &TrapFrame, trap: &crate::trap::Trap) -> (u32, i32, u64) {
    use crate::trap::Trap;
    use ferrix_linux_abi::types::{SIGBUS, SIGFPE, SIGILL, SIGSEGV, SIGTRAP};

    /// `si_code`: raised by the kernel for its own reasons.
    const SI_KERNEL: i32 = 0x80;
    /// `SIGSEGV`: nothing mapped at the address.
    const SEGV_MAPERR: i32 = 1;
    /// `SIGSEGV`: mapped, and the access refused.
    const SEGV_ACCERR: i32 = 2;
    /// `SIGBUS`: a misaligned address.
    const BUS_ADRALN: i32 = 1;
    /// `SIGILL`: an illegal operand, which is what Linux reports for `#UD`.
    const ILL_ILLOPN: i32 = 2;
    /// `SIGFPE`: an integer divided by zero.
    const FPE_INTDIV: i32 = 1;

    match trap {
        Trap::PageFault(fault) if fault.present => (SIGSEGV, SEGV_ACCERR, fault.address),
        Trap::PageFault(fault) => (SIGSEGV, SEGV_MAPERR, fault.address),
        Trap::IllegalInstruction => (SIGILL, ILL_ILLOPN, frame.rip),
        _ => match frame.vector {
            0 => (SIGFPE, FPE_INTDIV, frame.rip),
            16 | 19 => (SIGFPE, SI_KERNEL, frame.rip),
            17 => (SIGBUS, BUS_ADRALN, 0),
            1 | 3 => (SIGTRAP, SI_KERNEL, 0),
            _ => (SIGSEGV, SI_KERNEL, 0),
        },
    }
}

/// Print the interrupted state.
///
/// Called only when the kernel is about to stop, so it prints everything: on a
/// machine with no debugger attached this is the entire post-mortem.
pub(crate) fn report_trap(frame: &TrapFrame) {
    use crate::console::println;

    println!(
        "  vector   {} ({}), error {:#x}",
        frame.vector,
        vector_name(frame.vector),
        frame.error_code
    );
    if frame.vector == 14 {
        println!("  cr2      {:#018x}", fault_address());
    }
    println!("  rip      {:#018x}  cs  {:#x}", frame.rip, frame.cs);
    println!("  rsp      {:#018x}  ss  {:#x}", frame.rsp, frame.ss);
    println!("  rflags   {:#018x}", frame.rflags);
    println!("  rax {:#018x}  rbx {:#018x}", frame.rax, frame.rbx);
    println!("  rcx {:#018x}  rdx {:#018x}", frame.rcx, frame.rdx);
    println!("  rsi {:#018x}  rdi {:#018x}", frame.rsi, frame.rdi);
    println!("  rbp {:#018x}  r8  {:#018x}", frame.rbp, frame.r8);
    println!("  r9  {:#018x}  r10 {:#018x}", frame.r9, frame.r10);
    println!("  r11 {:#018x}  r12 {:#018x}", frame.r11, frame.r12);
    println!("  r13 {:#018x}  r14 {:#018x}", frame.r13, frame.r14);
    println!("  r15 {:#018x}", frame.r15);
    println!(
        "  from     {}",
        if frame.came_from_user() {
            "user mode"
        } else {
            "the kernel"
        }
    );
}

/// Step the return address over a breakpoint.
///
/// Nothing to do: `int3` pushes the address of the *following* instruction, so
/// returning already continues. `AArch64`'s `brk` does not, and its counterpart
/// has to add four — which is why this exists rather than the generic
/// dispatcher simply returning.
pub(crate) const fn advance_past_breakpoint(_frame: &mut TrapFrame) {}

/// Raise a breakpoint, so the boot self-check can prove the trap path runs.
pub(crate) fn breakpoint() {
    // SAFETY: `int3` raises vector 3, for which the IDT holds a gate. It has no
    // effect other than entering the handler, which returns to the instruction
    // after it.
    unsafe {
        core::arch::asm!("int3", options(nomem, nostack));
    }
}
