#!/usr/bin/env python3
"""The SOUP register, generated from the dependency graph that actually ships.

IEC 62304 calls third-party code in a device SOUP -- software of unknown
provenance -- and §5.3.3, §7.1.2 and §8.1.2 require every item of it to be
identified by title, manufacturer and version, with its published anomaly list
evaluated against the device's hazards. For a Class C item that evaluation is
the difference between a dependency and a finding.

Two facts, both measured here rather than asserted:

  1. **The certified item contains no SOUP.** `ferrix-kernel` and `ferrix-boot`
     link no external crate on any of the three architectures. Everything in
     the shipping graph is first-party code in this repository, developed under
     the lifecycle the rest of docs/certification describes. That is the single
     most valuable sentence in this file, so the gate below re-establishes it
     on every run instead of letting it be a thing that used to be true.

  2. **The host-side crates are tools, not SOUP.** The 21 external crates in
     `Cargo.lock` build, test and package the item; none is in it. They are
     classified in TOOLS.md under EN 50716 §6.7 and DO-330 instead, which asks
     a different and more tractable question -- can this tool introduce an
     undetected error into the product -- than 62304 asks of SOUP.

    python3 scripts/gen-soup.py            # write docs/certification/SOUP.md
    python3 scripts/gen-soup.py --check    # fail if it is stale or SOUP appeared
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "certification" / "SOUP.md"

# The shipping graph: every binary that is part of the certified item, against
# every target it is built for. A crate that appears in none of these is not in
# the device, whatever else it is in.
SHIPPING = [
    ("ferrix-kernel", "x86_64-unknown-none"),
    ("ferrix-kernel", "aarch64-unknown-none-softfloat"),
    ("ferrix-kernel", "armv7a-none-eabi"),
    ("ferrix-boot", "x86_64-unknown-uefi"),
    ("ferrix-boot", "aarch64-unknown-uefi"),
    ("ferrix-boot", "armv7-unknown-linux-musleabi"),
]


def shipping_externals() -> dict[tuple[str, str], list[str]]:
    """External crates reachable from each shipping binary."""
    found: dict[tuple[str, str], list[str]] = {}
    for package, target in SHIPPING:
        result = subprocess.run(
            ["cargo", "tree", "-p", package, "--edges", "normal",
             "--prefix", "none", "--target", target],
            cwd=ROOT, capture_output=True, text=True,
        )
        if result.returncode != 0:
            # A tree that errors must not read as "no dependencies found":
            # that turns a broken manifest into an empty SOUP register, which
            # is the exact failure this file exists to prevent.
            raise SystemExit(
                f"gen-soup: cargo tree failed for {package} on {target}:\n"
                f"{result.stderr.strip()}"
            )
        names = {
            line.split()[0]
            for line in result.stdout.splitlines()
            if line.strip() and not line.startswith(" ")
        }
        found[(package, target)] = sorted(n for n in names if not n.startswith("ferrix-"))
    return found


def host_crates() -> list[dict]:
    """Every external crate in the workspace graph, with its metadata."""
    blob = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--all-features"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    meta = json.loads(blob)
    members = set(meta["workspace_members"])
    return sorted(
        (
            {
                "name": p["name"],
                "version": p["version"],
                "license": p.get("license") or "(unstated)",
                "repository": p.get("repository") or "",
            }
            for p in meta["packages"]
            if p["id"] not in members and p.get("source")
        ),
        key=lambda p: p["name"],
    )


def render(ship: dict[tuple[str, str], list[str]], host: list[dict]) -> str:
    lines = [
        "# SOUP register",
        "",
        "*Generated by `scripts/gen-soup.py`. Do not edit: run the script.*",
        "",
        "IEC 62304 §5.3.3 requires every item of software of unknown provenance",
        "in the device to be identified, and §7.1.2 requires its published",
        "anomaly list to be evaluated against the item's hazards -- which are",
        "not yet analysed (FINDINGS.md, F-20). This register is generated from the",
        "dependency graph rather than maintained by hand, because a register",
        "that is edited separately from the manifest it describes is a register",
        "that is wrong.",
        "",
        "## 1. SOUP in the certified item",
        "",
        "| Binary | Target | External crates |",
        "|---|---|---:|",
    ]
    total = 0
    for (package, target), names in ship.items():
        total += len(names)
        shown = ", ".join(names) if names else "**none**"
        lines.append(f"| `{package}` | `{target}` | {shown} |")

    lines += [
        "",
        f"**Total SOUP in the item: {total}.**",
        "",
    ]
    if total == 0:
        lines += [
            "The item contains no software of unknown provenance. Every line in",
            "the shipping graph is first-party code in this repository, written",
            "against the design in `docs/ARCHITECTURE.md` and the model in",
            "`docs/sysml/`, under the conventions and gates this repository",
            "enforces on every commit. That is a lifecycle in practice; it is",
            "not yet one written down in the terms §5 asks for (F-28).",
            "",
            "This is worth stating plainly because it is the position Linux",
            "structurally cannot reach: a Linux-based medical device classifies",
            "the kernel itself as SOUP, since §5 lifecycle evidence cannot be",
            "produced retroactively for code developed elsewhere. The obligation",
            "that dominates a Class C submission built on Linux is, here, empty.",
            "",
            "It is not an accident and it is not free. `deny.toml` keeps the",
            "dependency budget near zero on purpose -- *code that runs in ring 0",
            "with no memory protection above it is code we want to have read* --",
            "and the cost is that `libs/` contains a hand-written ACPI parser, a",
            "device-tree parser, a btrfs implementation and a TCP stack.",
            "",
        ]
    else:
        lines += [
            "Each crate above is SOUP and needs, per §5.3.3, a documented",
            "functional and performance specification, and per §7.1.2 an",
            "evaluation of its published anomaly list against this item's",
            "hazards. **That evaluation is not yet written.**",
            "",
        ]

    lines += [
        "## 2. Host-side crates — tools, not SOUP",
        "",
        f"The {len(host)} external crates below are in `Cargo.lock` and build,",
        "test or package the item without being part of it. 62304 does not",
        "reach them; they are classified as tools in [TOOLS.md](TOOLS.md) under",
        "EN 50716 §6.7 and DO-330, where the question is whether a defect could",
        "put an undetected error into the product.",
        "",
        "| Crate | Version | Licence |",
        "|---|---|---|",
    ]
    for crate in host:
        lines.append(f"| `{crate['name']}` | {crate['version']} | {crate['license']} |")

    lines += [
        "",
        "Advisories against all of them are checked on every run of",
        "`cargo deny check` (`deny.toml`), whose `advisories.ignore` list is",
        "empty on purpose and whose `yanked` setting is `deny`.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if stale")
    args = parser.parse_args()

    ship = shipping_externals()
    rendered = render(ship, host_crates())

    leaked = {k: v for k, v in ship.items() if v}
    if leaked:
        print(
            "gen-soup: the certified item has acquired SOUP. An external crate\n"
            "  in ring 0 is third-party code inside the trusted base, and IEC\n"
            "  62304 §7.1.2 wants its anomaly list evaluated against every\n"
            "  hazard before it ships:",
            file=sys.stderr,
        )
        for (package, target), names in leaked.items():
            print(f"    {package} [{target}]: {', '.join(names)}", file=sys.stderr)
        return 1

    if args.check:
        if not OUTPUT.exists():
            print(f"gen-soup: {OUTPUT.relative_to(ROOT)} is missing", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                f"gen-soup: {OUTPUT.relative_to(ROOT)} is stale. Run\n"
                f"  python3 scripts/gen-soup.py",
                file=sys.stderr,
            )
            return 1
        print(f"gen-soup: register current, no SOUP in the item")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"gen-soup: wrote {OUTPUT.relative_to(ROOT)}, no SOUP in the item")
    return 0


if __name__ == "__main__":
    sys.exit(main())
