#!/usr/bin/env python3
"""Sort the uncovered statements into the categories DO-178C asks about.

Table A-7 wants every statement either exercised by a requirements-based test
or justified as unreachable. `scripts/coverage-report.py --residual` produces
the list; this sorts it, because 1,278 line numbers is a number and not an
argument.

The categories, in the order the analysis applies them:

  other-architecture   Code for an architecture the measured run was not.
                       `iommu/smmuv3.rs` is AArch64's IOMMU and no x86-64 run
                       can reach it. **Legitimately unreachable, per
                       configuration** -- and the same statements are ordinary
                       covered code on the architecture that owns them, which
                       is why the justification has to be made per
                       configuration rather than once.

  failure-path         Reached only when the kernel is stopping: the panic
                       report, the catalogue, the backtrace walker.
                       Legitimately unreachable in a passing run, and testing
                       it means deliberately crashing.

  absent-hardware      Enumeration and setup for devices the measured machine
                       does not have. Unreachable *on this machine*, which is
                       weaker than the first category: a different QEMU
                       invocation would reach some of it.

  needs-a-test         Everything else. This is the real work, and it is the
                       number that has to reach zero.

The first two are arguments. The third is a configuration statement. Only the
fourth is a gap, and separating them is the whole point: a single percentage
cannot be argued with and these four numbers can.

    python3 scripts/gen-coverage-justification.py
    python3 scripts/gen-coverage-justification.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESIDUAL = ROOT / "docs" / "certification" / "coverage-residual-x86_64.json"
OUTPUT = ROOT / "docs" / "certification" / "COVERAGE-RESIDUAL.md"

MEASURED_ARCH = "x86_64"

# Files belonging to an architecture other than the measured one, or to a
# board the measured machine is not.
OTHER_ARCH_MARKERS = (
    "arch/aarch64/",
    "arch/armv7a/",
    "arch/gicv2.rs",
    "arch/pl011.rs",
    "arch/stm32_usart.rs",
    "iommu/smmuv3.rs",
    "stm32mp1",
)
FAILURE_PATH = ("panic.rs", "panic/", "backtrace.rs")
ABSENT_HARDWARE = ("device.rs", "pci.rs", "pci/", "acpi.rs", "fdt.rs", "iommu/vtd.rs")


def categorise(path: str) -> str:
    if any(marker in path for marker in OTHER_ARCH_MARKERS):
        return "other-architecture"
    if any(path.endswith(m) or m in path for m in FAILURE_PATH):
        return "failure-path"
    if any(path.endswith(m) or path.startswith(m) for m in ABSENT_HARDWARE):
        return "absent-hardware"
    return "needs-a-test"


HEADINGS = {
    "other-architecture": (
        "Unreachable on the measured architecture",
        "Justified. These statements belong to another architecture or another "
        "board, and no run on {arch} can reach them. The same code is ordinary "
        "covered code where it belongs, so this justification is per "
        "configuration and the other architectures owe their own.",
    ),
    "failure-path": (
        "Reached only when the kernel is stopping",
        "Justified. The panic report, its catalogue and the backtrace walker "
        "run when the kernel has already decided to stop. Exercising them means "
        "crashing deliberately, which the boot gates do not do -- and a passing "
        "run that reached them would be a failing run.",
    ),
    "absent-hardware": (
        "Hardware the measured machine does not have",
        "**Not a justification, a configuration statement.** Enumeration and "
        "setup for devices this QEMU invocation does not present. A different "
        "machine would reach some of it, so the honest closure is either to "
        "measure on a machine that has the hardware or to state which devices "
        "the claim excludes.",
    ),
    "needs-a-test": (
        "Needs a test",
        "**The real gap.** No argument covers these; they are reachable on the "
        "measured configuration and nothing exercised them. This is the number "
        "that has to reach zero for DO-178C table A-7 objective 5.",
    ),
}


def render(residual: dict) -> str:
    buckets: dict[str, dict[str, int]] = {name: {} for name in HEADINGS}
    for path, entry in residual["files"].items():
        buckets[categorise(path)][path] = len(entry["lines"])

    total = residual["unreached"]
    lines = [
        "# Coverage residual",
        "",
        "*Generated by `scripts/gen-coverage-justification.py`. Do not edit.*",
        "",
        f"The **{total}** statements in the certified item that the measured "
        f"runs did not reach, sorted into the categories DO-178C table A-7 "
        f"asks about. Measured on {MEASURED_ARCH}, "
        f"{residual['profile']} profile.",
        "",
        "| Category | Statements | Share |",
        "|---|---:|---:|",
    ]
    for name in HEADINGS:
        count = sum(buckets[name].values())
        lines.append(
            f"| {HEADINGS[name][0]} | {count} | {100.0 * count / (total or 1):.0f}% |"
        )

    justified = sum(
        sum(buckets[n].values()) for n in ("other-architecture", "failure-path")
    )
    gap = sum(buckets["needs-a-test"].values())
    lines += [
        "",
        f"**{justified} are argued, {gap} are a gap**, and the remainder is a "
        "statement about which machine was measured rather than either.",
        "",
    ]

    for name, (heading, rationale) in HEADINGS.items():
        entries = sorted(buckets[name].items(), key=lambda kv: -kv[1])
        count = sum(buckets[name].values())
        lines += [
            "---",
            "",
            f"## {heading} — {count} statements",
            "",
            rationale.format(arch=MEASURED_ARCH),
            "",
        ]
        if not entries:
            lines += ["None.", ""]
            continue
        lines += ["| Statements | Ring | File |", "|---:|---|---|"]
        for path, n in entries[:25]:
            ring = residual["files"][path]["ring"]
            lines.append(f"| {n} | `{ring}` | `{path}` |")
        if len(entries) > 25:
            rest = sum(n for _, n in entries[25:])
            lines.append(f"| {rest} | | *and {len(entries) - 25} more files* |")
        lines.append("")

    lines += [
        "---",
        "",
        "## What this does not do",
        "",
        "It sorts by file, not by statement. A file in *needs-a-test* may hold "
        "individual lines that are genuinely unreachable -- a defensive `else` "
        "on an invariant the type system already forces -- and a file in a "
        "justified category may hold a line that is not. Closing F-10 means "
        "walking the fourth category line by line; this says which lines to "
        "walk and which not to bother with, which is the part a percentage "
        "could not.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not RESIDUAL.is_file():
        print(
            f"gen-coverage-justification: {RESIDUAL.relative_to(ROOT)} is missing.\n"
            f"  Produce it with `coverage-report.py --residual`.",
            file=sys.stderr,
        )
        return 1

    rendered = render(json.loads(RESIDUAL.read_text(encoding="utf-8")))

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                "gen-coverage-justification: "
                f"{OUTPUT.relative_to(ROOT)} is stale. Run the generator.",
                file=sys.stderr,
            )
            return 1
        print("gen-coverage-justification: current")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"gen-coverage-justification: wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
