#!/usr/bin/env python3
"""Turn libxkbcommon's own keymap into the tables the compositor's seat reads.

A `wl_keyboard` hands its client a keymap and then sends raw keycodes; the
client compiles the keymap with libxkbcommon and reads every letter out of it.
So the keymap has to be a real one, and the bits in `wl_keyboard.modifiers`
have to be the ones that keymap declares -- a modifier index is a property of
the keymap, not a constant.

`compositor/xkb/probe/keymap.txt` is what libxkbcommon says, printed by a
committed probe (`probe/keymap.c`, `probe/keymap.sh`) on a host that has it.
This turns that into two committed files: the keymap text the compositor
sends, and a Rust table of every key's name, its keysyms and the modifiers it
makes.

Neither may be written by hand, and neither is generated from whatever
libxkbcommon the builder happens to have: the probe's output is committed, so
a change to the keymap is a change to a file somebody reviewed.

Usage:
    python3 scripts/gen-xkb-tables.py           # write the files
    python3 scripts/gen-xkb-tables.py --check   # fail if they are stale
"""

import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROBE = ROOT / "compositor" / "xkb" / "probe" / "keymap.txt"
OUT = ROOT / "compositor" / "xkb" / "src"
KEYMAP = OUT / "us.xkb"
TABLES = OUT / "generated.rs"


def read_probe():
    """The probe's three sections: its banner, the modifiers, the keys, the keymap."""
    text = PROBE.read_text(encoding="utf-8")
    lines = text.split("\n")
    if not lines or not lines[0].startswith("# "):
        raise SystemExit(f"{PROBE} has no banner; run probe/keymap.sh")
    banner = lines[0][2:].strip()

    sections = {}
    name = None
    for line in lines[1:]:
        if line.startswith("## "):
            name = line[3:].split()[0]
            sections[name] = []
            continue
        if name is not None:
            sections[name].append(line)

    for wanted in ("modifiers", "keys", "keymap"):
        if wanted not in sections:
            raise SystemExit(f"{PROBE} has no `## {wanted}` section")

    modifiers = []
    for line in sections["modifiers"]:
        if not line.strip():
            continue
        label, index = line.split()
        modifiers.append((label, None if index == "-" else int(index)))

    keys = []
    for line in sections["keys"]:
        if not line.strip():
            continue
        code, key, plain, shifted, held, locked = line.split()
        keys.append(
            (
                int(code),
                key,
                None if plain == "-" else plain,
                None if shifted == "-" else shifted,
                int(held, 0),
                int(locked, 0),
            )
        )

    # The keymap is the rest of the file verbatim, including its blank lines.
    # The probe prints its length so a truncated file is caught here rather
    # than by a client that cannot compile it.
    declared = None
    for line in lines:
        if line.startswith("## keymap "):
            declared = int(line.split()[2])
    keymap = "\n".join(sections["keymap"])
    if keymap.endswith("\n"):
        keymap = keymap[:-1]
    keymap += "\n"
    if declared is not None and len(keymap) != declared:
        raise SystemExit(
            f"{PROBE}'s keymap is {len(keymap)} bytes, not the {declared} it declares"
        )
    return banner, modifiers, keys, keymap


def escaped(text):
    """`text` as a Rust string literal's contents."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def tables(banner, modifiers, keys):
    """The generated Rust."""
    out = []
    add = out.append
    add(f"""// @generated by scripts/gen-xkb-tables.py from
// compositor/xkb/probe/keymap.txt. Do not edit: run the probe and then
//
//     python3 scripts/gen-xkb-tables.py
//
// which `cargo xtask check` verifies.

//! The keymap's own tables: which bit each modifier is, and what each key is.
//!
//! From {escaped(banner)}.

use crate::Key;
""")

    add("/// The keymap these tables came from, as the probe named it.")
    add(f'pub const SOURCE: &str = "{escaped(banner)}";\n')

    add("""// Each modifier's bit in `wl_keyboard.modifiers`, as this keymap orders
// them. A modifier the keymap does not declare has no bit and is zero, so
// that a mask built from it matches nothing rather than matching `Shift`.""")
    for label, index in modifiers:
        mask = 0 if index is None else 1 << index
        name = {
            "Shift": "SHIFT",
            "Lock": "LOCK",
            "Control": "CONTROL",
            "Mod1": "MOD1",
            "Mod2": "MOD2",
            "Mod3": "MOD3",
            "Mod4": "MOD4",
            "Mod5": "MOD5",
        }.get(label, label.upper())
        where = "no index" if index is None else f"index {index}"
        add(f"/// `{label}`, {where} in this keymap.")
        add(f"pub const {name}: u32 = {mask:#x};\n")

    add("""/// Every key the keymap names, in order of its evdev code.
///
/// `held` is the modifiers pressing it makes depressed and `locked` the ones
/// it leaves locked once it has been pressed and released, both asked of
/// libxkbcommon's own state machine rather than worked out from the key's
/// name.
///
/// A `static` rather than a `const`: a const this size would be copied into
/// every place that read it.""")
    add(f"pub static KEYS: [Key; {len(keys)}] = [")
    for code, key, plain, shifted, held, locked in keys:
        plain_text = "None" if plain is None else f'Some("{escaped(plain)}")'
        shifted_text = "None" if shifted is None else f'Some("{escaped(shifted)}")'
        add(
            f'    Key {{ code: {code}, name: "{escaped(key)}", '
            f"plain: {plain_text}, shifted: {shifted_text}, "
            f"held: {held:#x}, locked: {locked:#x} }},"
        )
    add("];")
    return "\n".join(out) + "\n"


def formatted(text):
    """`text` through rustfmt, so the file reads like the rest of the tree."""
    with tempfile.NamedTemporaryFile("w", suffix=".rs", delete=False) as handle:
        handle.write(text)
        handle.flush()
        result = subprocess.run(
            ["rustfmt", "--edition", "2024", "--emit", "files", handle.name],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise SystemExit(f"rustfmt refused the generated code:\n{result.stderr}")
        return pathlib.Path(handle.name).read_text(encoding="utf-8")


def main():
    check = "--check" in sys.argv[1:]
    if not PROBE.is_file():
        raise SystemExit(f"{PROBE} is missing; run compositor/xkb/probe/keymap.sh")
    banner, modifiers, keys, keymap = read_probe()
    wanted = {KEYMAP: keymap, TABLES: formatted(tables(banner, modifiers, keys))}

    stale = [
        path
        for path, text in wanted.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != text
    ]
    if check:
        if stale:
            for path in stale:
                print(f"{path.relative_to(ROOT)} is stale", file=sys.stderr)
            print("run `python3 scripts/gen-xkb-tables.py`", file=sys.stderr)
            return 1
        print(f"gen-xkb-tables: {len(keys)} keys current")
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8")
    print(f"gen-xkb-tables: wrote {len(keys)} keys and a {len(keymap)}-byte keymap")
    return 0


if __name__ == "__main__":
    sys.exit(main())
