#!/usr/bin/env python3
"""Generate the architecture document from the SysML v2 model.

`docs/sysml/` is a model of this system, and `docs/ARCHITECTURE.md` is the
prose it indexes. Neither is a document you can hand somebody: the model is
notation, and the prose deliberately argues rather than enumerates. This writes
the third thing -- the enumeration -- and writes it from the model, so it
cannot drift from what the model says.

Four outputs, one pass:

    docs/generated/ARCHITECTURE.md     the document, readable on GitHub
    docs/generated/architecture.html   the same, standalone, no network
    docs/generated/model.json          the parsed model, for other tools
    docs/generated/diagrams/*.svg      each figure on its own, for embedding

The diagrams are drawn twice from one graph and never by hand: the Markdown
carries each figure as a Mermaid fence, which GitHub renders itself, and the
HTML carries the same figure laid out by `scripts/sysml/layout.py` and inlined
as SVG, because that page has to open from a file:// path. The `.svg` files are
that second drawing, written out separately for anything that wants one figure
rather than the document.

The outputs are committed, and `--check` regenerates into memory and compares.
That is the whole gate: editing the model without regenerating fails CI, and
the fix is to run this command. A document generated only in CI would be a
document nobody reads, and one generated by hand is one that goes stale between
the commit that changed the model and the commit that noticed.

Reproducible means byte-identical, so nothing here writes a timestamp, a
hostname, a path outside the repository, or a tool version. What identifies a
build is the digest of the inputs, which is printed and embedded.

Usage:
    python3 scripts/gen-arch-doc.py              # write the outputs
    python3 scripts/gen-arch-doc.py --check      # fail if they are stale
    python3 scripts/gen-arch-doc.py --out DIR    # write somewhere else
    python3 scripts/gen-arch-doc.py --lenient    # tolerate unparsed lines
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from sysml import load  # noqa: E402
from sysml import emit_json, render_html, render_markdown, render_svg, sections  # noqa: E402

MODEL_DIR = pathlib.Path("docs/sysml")
OUT_DIR = pathlib.Path("docs/generated")

MARKDOWN = "ARCHITECTURE.md"
HTML = "architecture.html"
JSON = "model.json"
DIAGRAMS = "diagrams"

BANNER = (
    "Generated from docs/sysml/ by scripts/gen-arch-doc.py. Do not edit: "
    "change the model and regenerate with `cargo xtask model-doc`."
)


def repository_root() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent.parent


def build(root: pathlib.Path, lenient: bool) -> tuple[dict[str, str], object]:
    paths = sorted((root / MODEL_DIR).glob("*.sysml"))
    if not paths:
        raise SystemExit(f"gen-arch-doc: no .sysml files under {MODEL_DIR}")

    model = load(paths, root)

    if model.unparsed and not lenient:
        print(
            f"gen-arch-doc: {len(model.unparsed)} declaration(s) the reader does not "
            "understand. The document would be missing them.\n",
            file=sys.stderr,
        )
        for element in model.unparsed[:20]:
            print(f"  {element.source}:{element.line}: {element.raw}", file=sys.stderr)
        print(
            "\nTeach scripts/sysml/parser.py the construct, or pass --lenient to "
            "generate anyway.",
            file=sys.stderr,
        )
        raise SystemExit(2)

    document = sections.build(model, banner=BANNER)
    figures = [block.figure for block in document.meta.get("figures", [])]
    outputs = {
        MARKDOWN: render_markdown.render(document),
        HTML: render_html.render(document),
        JSON: emit_json.render(model, figures),
    }
    for block in document.meta.get("figures", []):
        outputs[block.file] = render_svg.render(block.figure, standalone=True)
    return outputs, model


def write(outputs: dict[str, str], out_dir: pathlib.Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in outputs.items():
        path = out_dir / name
        path.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" so a Windows checkout does not produce CRLF and fail
        # the line-endings gate on a file nobody typed.
        path.write_text(text, encoding="utf-8", newline="\n")
    _prune(outputs, out_dir)


def _prune(outputs: dict[str, str], out_dir: pathlib.Path) -> None:
    """Delete a diagram the model no longer draws.

    Renaming a part renames its figure, and without this the old file would sit
    in `docs/generated/` for ever, still committed, still wrong, and still
    passing the check -- which only looks at the files the model asks for.
    """
    directory = out_dir / DIAGRAMS
    if not directory.is_dir():
        return
    expected = {name.rsplit("/", 1)[-1] for name in outputs if name.startswith(DIAGRAMS + "/")}
    for path in sorted(directory.glob("*.svg")):
        if path.name not in expected:
            path.unlink()


def check(outputs: dict[str, str], out_dir: pathlib.Path) -> int:
    stale: list[str] = []
    directory = out_dir / DIAGRAMS
    if directory.is_dir():
        expected = {name.rsplit("/", 1)[-1] for name in outputs if name.startswith(DIAGRAMS + "/")}
        for path in sorted(directory.glob("*.svg")):
            if path.name not in expected:
                stale.append(f"{path}: no figure draws this any more")
    for name, text in outputs.items():
        path = out_dir / name
        if not path.exists():
            stale.append(f"{path}: missing")
            continue
        current = path.read_text(encoding="utf-8")
        if current != text:
            stale.append(f"{path}: out of date ({_diff_summary(current, text)})")
    if stale:
        print("gen-arch-doc: the generated document does not match the model.\n")
        for line in stale:
            print(f"  {line}")
        print("\nRun `cargo xtask model-doc` (or python3 scripts/gen-arch-doc.py) and commit the result.")
        return 1
    return 0


def _diff_summary(current: str, expected: str) -> str:
    current_lines = current.splitlines()
    expected_lines = expected.splitlines()
    for index, (left, right) in enumerate(zip(current_lines, expected_lines), 1):
        if left != right:
            return f"first difference at line {index}"
    return f"{len(current_lines)} lines committed, {len(expected_lines)} expected"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the architecture document from docs/sysml/.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the committed outputs are stale",
    )
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=None,
        help=f"output directory (default: {OUT_DIR})",
    )
    parser.add_argument(
        "--lenient",
        action="store_true",
        help="generate even when the reader did not understand a declaration",
    )
    parser.add_argument("--quiet", action="store_true", help="print nothing on success")
    arguments = parser.parse_args()

    root = repository_root()
    outputs, model = build(root, arguments.lenient)
    out_dir = arguments.out if arguments.out is not None else root / OUT_DIR

    if arguments.check:
        return check(outputs, out_dir)

    write(outputs, out_dir)
    if not arguments.quiet:
        counts = model.maturity_counts()
        figures = sum(1 for name in outputs if name.startswith(DIAGRAMS + "/"))
        print(f"gen-arch-doc: {len(model.files)} files, {sum(1 for _ in model.walk())} elements")
        print(
            "  "
            + ", ".join(f"{count} {name}" for name, count in counts.items() if count)
            + f", {len(model.deferred())} deferred"
        )
        print(f"  digest {model.digest[:16]}")
        for name in outputs:
            if name.startswith(DIAGRAMS + "/"):
                continue
            path = (out_dir / name).relative_to(root) if out_dir.is_relative_to(root) else out_dir / name
            print(f"  wrote {path}")
        print(f"  wrote {figures} diagrams under {DIAGRAMS}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
